#!/bin/bash

eval $(ssh-agent)

rm ~/.config/fish/setup_ssh_agent
echo "set -x SSH_AUTH_SOCK $SSH_AUTH_SOCK" > ~/.config/fish/setup_ssh_agent
echo "set -x SSH_AGENT_PID $SSH_AGENT_PID" >> ~/.config/fish/setup_ssh_agent
